languageCode = "ko"
languageName = "한글"
weight = 1
title = "jssong84 | Notion, ESP32"

[params]
  displayName = "한글"
  isoCode = "ko"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/logo.001.png"
  secondaryLogo = "img/logo.002.png"
  description = "jssong84 | Notion, ESP32"
  # copyright = "Copy, _right?_ :thinking_face:"

  [params.author]
  name = "jssong84"
  image = "img/profile.png"
  headline = "꿈의 정상에서 만나요."
  bio = "꿈의 정상에서 만나요."
  links = [
    { instagram = "https://www.instagram.com/jssong84/" },
    { linkedin = "https://www.linkedin.com/in/jssong84/" },
    { youtube = "https://www.youtube.com/@carstaurant" },
    { threads = "https://www.threads.com/@jssong84" },
    { email = "mailto:jssong.zenith@gmail.com" },

    #{ rss = "https://n9o.xyz/index.xml" },    
    #{ x-twitter = "https://twitter.com/nunocoracao" },
    #{ github = "https://github.com/nunocoracao" },
    #{ medium = "https://medium.com/@nunocoracao" },
    #{ hackernews = "https://news.ycombinator.com/user?id=nunocoracao"},
    #{ mastodon = "https://masto.ai/@nunocoracao" },
    #{ goodreads = "http://goodreads.com/nunocoracao" },
    #{ reddit = "https://reddit.com/user/nunoheart" },
    #{ telegram = "https://t.me/nunocoracao" },
    #{ music = "/music" },
  ]